---
  - name: install nginx package
    apt: pkg=nginx state=installed

  - name: remove default nginx site
    file: "path=/etc/nginx/{{item}}/default state=absent"
    with_items:
      - sites-enabled
      - sites-available

  - name: copy nginx conf
    copy: "src=templates/shop.nginx.{{ rails_env }}.conf dest={{ item }}"
    with_items:
      - /etc/nginx/sites-enabled/default.conf
      - /etc/nginx/sites-available/default.conf

  - name: copy upstart script
    copy: "src=templates/nginx.upstart.conf dest=/etc/init/nginx.conf"
