---
  - name: install redis
    apt: "pkg={{ item }} state=installed"
    with_items:
      - redis-server

  - name: copy redis upstart
    copy: src=templates/redis.upstart.conf dest=/etc/init/redis.conf
