- name: Add deployment user
  action: "user name={{ user }} password={{ user_password }} state=present shell=/bin/bash"

- name: Add ssh key for that user
  authorized_key: "user={{ user }} key='{{ lookup('file', '~/.ssh/id_rsa.pub') }}'"

- name: Remove sudo group rights
  action: lineinfile dest=/etc/sudoers regexp="^%sudo" state=absent

- name: Add deploy user to sudoers
  action: 'lineinfile dest=/etc/sudoers regexp="{{ user }} ALL" line=" {{ user }} ALL=(ALL) NOPASSWD:ALL" state=present'

- name: Disallow password authentication
  action: lineinfile dest=/etc/ssh/sshd_config regexp="^PasswordAuthentication" line="PasswordAuthentication no" state=present
  notify: Restart ssh

- name: Disallow root SSH access
  action: lineinfile dest=/etc/ssh/sshd_config regexp="^PermitRootLogin" line="PermitRootLogin no" state=present
  notify: Restart ssh

- name: Make user owner of home
  sudo: True
  shell: "chown {{ user }}:root /home/{{ user }}"
